# Generated by Django 3.2.24 on 2024-03-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=50)),
                ('event_name', models.CharField(max_length=50)),
                ('event_choice', models.CharField(choices=[('ライブ', 'ライブ'), ('握手会', '握手会'), ('オンラインイベント', 'オンラインイベント'), ('オフラインイベント', 'オフラインイベント'), ('その他', 'その他')], max_length=50)),
                ('content', models.TextField()),
                ('good_count', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
